services:
  mysql:
    image: mysql:8.0
    container_name: fc_ch3_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./configs/database.sql:/docker-entrypoint-initdb.d/database.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fc_ch3_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

